alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
alias ansible_pi_ip='sed -i "s#lampi ansible_user=pi ansible_ssh_host=.*#lampi ansible_user=pi ansible_ssh_host=$pi_ip#g" ~/connected-devices/ansible/inventory.ini'
alias bal='nano ~/.bash_aliases'
alias brc='nano ~/.bashrc'
alias cp='cp -v'
alias curbrt='cat /sys/devices/pci0000:00/0000:00:02.0/drm/card0/card0-eDP-1/intel_backlight/actual_brightness'
alias egrep='egrep --color=auto'
alias end='tail -'
alias evim='emacs -nw'
alias fgrep='fgrep --color=auto'
alias findtxt='grep -Rnw . -e '
alias grep='grep --color=auto'
alias grepn='grep -n'
alias ie='/mnt/c/Program\ Files\ \(x86\)/Internet\ Explorer/iexplore.exe'
alias ifind='find . -iname'
alias l='ls -CF'
alias la='ls -A'
alias lakewood='sshgpr && ssh pi@$gpr_ip'
alias ll='ls -alF'
alias lp='stat -c "%a %n" *'
alias ls='ls --color=auto -hN --group-directories-first'
alias mdas_ssh='ssh mdas@192.168.1.113'
alias more='less -FX'
alias n='nano -ET4'
alias notepad='/mnt/c/Windows/System32/notepad.exe'
alias pinstall='pip install --user'
alias relay_off='rostopic pub -1 /relay_state std_msgs/Bool False'
alias relay_on='rostopic pub -1 /relay_state std_msgs/Bool True'
alias restart_ec2='se sudo /sbin/shutdown -r now'
alias restart_pi='spi sudo /sbin/shutdown -r now'
alias rmup='rm *.upload -i'
alias scat='socat -d -d pty,raw,echo=0,link=in pty,raw,echo=0,link=out'
alias se='ssh ubuntu@54.156.244.126'
alias se2='ssh 18.233.0.192'
alias show_permissions='stat -c '\''%a %n'\'' *'
alias shutdown_ec2='se sudo /sbin/shutdown -h now'
alias shutdown_pi='spi sudo /sbin/shutdown -h now'
alias sl='ssh $load_test_ip'
alias spi='ssh pi@$(tail -1 ~/pi_ip.log)'
alias spot='/mnt/c/Users/ragha/AppData/Roaming/Spotify/Spotify.exe '
alias ssh_agent_pi='sed -i.bak "1 s/^.*$/Host "$pi_ip"/" .ssh/config'
alias st='ssh $target'
alias start_spacebridge='/home/raghav/Downloads/spacebridge-0.4.2-x86_64-pc-linux-gnu/bin/spacebridge --apikey 1kxVrwcA01seNNZXPRFbnMVXFw1Glm -f 473553:22:5022 --text-mode --verbose'
alias termbin_all='for file in *.upload; do termbin "$file"; done'
alias volt='python /home/raghav/_Downloads/phidget/python/VoltageInput.py'
